// Must be the first thing imported anywhere in the backend — every other module that reads
// process.env (notably the Prisma client, which reads DATABASE_URL on construction) depends on
// dotenv having already run. index.ts enforces this by importing env.ts before anything else.
import 'dotenv/config';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const backendRoot = path.resolve(__dirname, '..');
const dataDir = path.join(backendRoot, 'data');

// Session secret persisted to a local file so restarts don't invalidate every session — only
// used when SESSION_SECRET isn't set (local/self-hosted dev). On Render, SESSION_SECRET is
// always set (auto-generated by the Blueprint), so this fallback never runs there.
function readOrCreateLocalSessionSecret(): string {
  const secretPath = path.join(dataDir, '.session_secret');
  fs.mkdirSync(dataDir, { recursive: true });
  try {
    return fs.readFileSync(secretPath, 'utf8').trim();
  } catch {
    const secret = crypto.randomBytes(32).toString('hex');
    fs.writeFileSync(secretPath, secret);
    return secret;
  }
}

export const config = {
  port: Number(process.env.PORT || 4000),
  host: process.env.HOST || '0.0.0.0',
  isProduction: process.env.NODE_ENV === 'production',
  sessionSecret: process.env.SESSION_SECRET || readOrCreateLocalSessionSecret(),
  // Master password for the cross-tenant /support console — unset by default, which disables
  // the feature entirely (see routes/support.routes.ts) rather than shipping with a backdoor
  // nobody explicitly configured.
  supportPassword: process.env.SUPPORT_ACCESS_PASSWORD || '',
  databaseUrl: process.env.DATABASE_URL,
  gmailUser: process.env.GMAIL_USER,
  gmailAppPassword: process.env.GMAIL_APP_PASSWORD,
  backendRoot,
  dataDir,
  distDir: path.resolve(backendRoot, '..', 'dist'),
};
